env:
  browser: true
  es6: true
  mocha: true
  jasmine: true
  jest: true
  jquery: true
extends:
  - crockford
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  quotes:
    - error
    - single
  require-jsdoc: off
  one-var: off
  no-undef: off
  no-use-before-define: off
  comma-dangle: ['error', 'always']
